package main

import (
	"flag"
	"log"
	"os"

	"github.com/connormckelvey/go-github-mockable/internal/generator"
)

func main() {
	var outputPath string
	flag.StringVar(&outputPath, "o", "client.gen.go", "")
	flag.Parse()

	w, _ := os.Create(outputPath)
	defer w.Close()

	w.WriteString("// Code generated by github.com/connormckelvey/go-github-mockable/cmd/generate. DO NOT EDIT.\n\n")

	err := generator.New().Generate(w)
	if err != nil {
		log.Fatal(err.Error())
	}
}
