name: Publish
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Publish
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          GOPROXY: proxy.golang.org
        run: go list -m "github.com/connormckelvey/go-github-mockable@${RELEASE_VERSION}"
